szuletesidatum = input('mikor születtél? ÉÉÉÉ-MM-NN: ')
csillagjegy = input('mi a csillagjegyed?')
vezeteknev = input("add meg a vezetékneved")
keresztnev = input("add meg a keresztneved")
print('A te neved', vezeteknev, keresztnev,'.' 'Ekkor születtél:', szuletesidatum, '.', 'Ez a csillagjegyed:', csillagjegy)